### PR TITLE
Fix `ParameterizedTests` suppressing `PreconditionViolationException`

### LINKED ISSUE #230: Java: JUnit5 ParameterizedTests suppress PreconditionViolationException and don't fail the tests
**Describe the bug**
When using JUnit5 `ParameterizedTest`s one can specify a display name for each test case with the optional `name`. It is also possible to use use formatter patterns like `"{0}"`. If by some reason the name string comes out empty or null or some other problems occurrs an exception is thrown:
> org.junit.platform.commons.PreconditionViolationException: displayName must not be null or blank

and the tests should fail. On Codewars on the other hand this exception is suppressed and the execution of further tests of that test method are aborted and no failure is issued. Of course this is not an issue for solvers but for authors and translators errors in the test setup can go unnoticed.

**To Reproduce**
```java
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class SampleTests {
	
	@ParameterizedTest(name = "{0}")
	@ValueSource(strings = {"a", "", "b"})
	void test(String s) {
		System.out.println(">>"+s+"<<");
	}
}
```

**Expected behavior**
Show the error to the author and indicate tests as failed. Problem might be that the error doesn't show up at the test case but on a higher level in the nested test Structure

**Screenshots**
Codewars output
Eclipse output

**Additional context**
Happens in Java 11 and 17. Java 8 runtime has no JUnit 5 available.
Stack trace of the error:
```stacktrace
org.junit.platform.commons.PreconditionViolationException: displayName must not be null or blank
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:299)
	at org.junit.platform.commons.util.Preconditions.notBlank(Preconditions.java:267)
	at org.junit.platform.engine.support.descriptor.AbstractTestDescriptor.<init>(AbstractTestDescriptor.java:89)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.<init>(JupiterTestDescriptor.java:74)
	at org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor.<init>(MethodBasedTestDescriptor.java:67)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.<init>(TestMethodTestDescriptor.java:86)
	at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor.<init>(TestTemplateInvocationTestDescriptor.java:48)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.createInvocationTestDescriptor(TestTemplateTestDescriptor.java:134)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$1(TestTemplateTestDescriptor.java:107)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:110)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:44)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

### PR DESCRIPTION
**Pull request by hobovsky**
Fixes https://github.com/codewars/runner/issues/230 .

Example test suite which showcases various possible test outcomes:

```java
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.assertEquals;
class SampleTests {

    @ParameterizedTest(name = "{0}")
    @ValueSource(strings = {"a", "x", "b"})
    void testSuccess(String s) {
        System.out.println(">>"+s+"<<");
        assertEquals(s, s);
    }


    @ParameterizedTest(name = "{0}")
    @ValueSource(strings = {"a", "x", "b"})
    void testFailingAssertion(String s) {
        System.out.println(">>"+s+"<<");
        assertEquals(s, s + s, "Incorrect answer for input: " + s);
    }

    @ParameterizedTest(name = "Test \"{0}\"")
    @ValueSource(strings = {"a", "", "b"})
    void testThrowing(String s) {
        System.out.println(">>"+s+"<<");
        assertEquals(s.charAt(0), s.charAt(0), "Incorrect answer for input: " + s);
    }

    @ParameterizedTest(name = "{0}")
    @ValueSource(strings = {"a", "", "b"})
    void testCrash(String s) {
        System.out.println(">>"+s+"<<");
        assertEquals(s, s);
    }
}
```

### CODE REVIEW

File: src/main/java/com/codewars/junit5/CodewarsListener.java [hunk 1]
```diff
@@ -21,193 +21,214 @@
...
+
+    private static void outputError(String kind, Throwable throwable) {
+        String msg = throwable.getMessage();
+        if (msg == null) {
+            System.out.printf("\n<ERROR::>Test %s\n", kind);
+            System.out.printf("\n<LOG:ESC:-Stack Trace>%s\n", formatMessage(readStackTrace(throwable)));
+        } else {
+            String formattedMessage = formatMessage(msg);
+            String formattedStackTrace = formatMessage(readStackTrace(throwable));
+            System.out.printf("\n<ERROR::>%s<:LF:><:LF:>Stack trace:<:LF:><:LF:>%s\n", formattedMessage, formattedStackTrace);
```
Comment (kazk) [inline src/main/java/com/codewars/junit5/CodewarsListener.java]: Is there a reason not to collapse the stack trace like above (L176)?

**Review by kazk — CHANGES_REQUESTED** [review]
I don't mind changing to use 4 spaces, but can you commit separately?

**Comment by hobovsky** [comment]
> I don't mind changing to use 4 spaces, but can you commit separately?

This was unintentional, IDE did this. I did notice the large diff, but I thought these were Windows line breaks. I will try to revert the change in whitespace.

File: src/main/java/com/codewars/junit5/CodewarsListener.java (hunk 1 above)
Comment (hobovsky) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: Well my reasoning was that a collapsed stacktrace does not necessarily represent a (potentially severe) problem with runtime but more a failing test case. I thought that since it's an internal error of JUnit, it deserves to crash hard. But it's just what I thought, can change it to whatever you prefer.

Comment (kazk) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: Makes sense. Can you still put them in a separate container? Just don't add `-`. I think that's more readable.

Comment (hobovsky) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: Here it is. I am not sure I like how the stacktrace now looks logically separate from the error, but if you prefer it this way, then fine.  
BTW stacktraces in log panel look much better than in the `ERROR::` panel due to lack of excessive line wrapping. Would it be possible to make the error panel behave in similar way as log panels? Maybe this would also solve the readability issue.

**Comment by hobovsky** [comment]
For comparison, this is how test result looks in IDE runner:

image

File: src/main/java/com/codewars/junit5/CodewarsListener.java (hunk 1 above)
Comment (kazk) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: Can you post a screenshot? I saw the original on Discord, but can you also repost that here, so it's easier to compare?

I'll look into the excessive line wrapping.

Comment (hobovsky) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: Not sure what screenshot exactly you want? Here's the `ERROR` with `LOG` vs a single `ERROR`:

image

image


Is this what you asked?

Comment (hobovsky) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: For comparison, here is with CSS property `white-space: pre`:

image

Comment (kazk) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: Yeah, the last one might be the best. I think "Stack Trace:" can be removed.

I'll fix the CSS and let you know.

Comment (kazk) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: Deployed the CSS change.

Comment (hobovsky) [reply src/main/java/com/codewars/junit5/CodewarsListener.java]: > Is there a reason not to collapse the stack trace like above (L176)?

Now I see what you mean, and it was a copy/paste mistake that `outputError` used collapsible `LOG::` in one branch, and `ERROR::` in another. I changed both branches in `outputError` to use `ERROR::` and I think that after your fix to CSS, it looks good.

`outputFailure` uses collapsed `LOG::` as it has been all the time.

**Review by kazk — APPROVED** [review]
